resource "aws_security_group" "security_group" {
  name = "${var.name}-security_group"
  description = "The ${var.name} security group generated by Terraform"
  
  vpc_id = var.vpc_id

  dynamic "ingress" {
    for_each = var.ports

    content {
      from_port = ingress.value
      to_port = ingress.value
      protocol = "tcp"
      cidr_blocks = ["0.0.0.0/0"]
    }
  }

  egress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    }
}

resource "aws_eip" "elastic_ip" {
  count = var.public_ip ? 1 : 0

  instance = aws_instance.ec2_instance.id
  associate_with_private_ip = var.private_ip
}

resource "aws_instance" "ec2_instance" {
    # Ubuntu 22.04 ami
    ami = "ami-053b0d53c279acc90"

    instance_type = "t3a.medium"
    
    key_name = var.key_name
    subnet_id = var.subnet_id
    vpc_security_group_ids = [ aws_security_group.security_group.id ]
    private_ip = var.private_ip

    tags = {
      Name = "cptc-ec2"
    }

    user_data = <<-EOF
        #!/bin/bash
        echo "ubuntu:ubuntu" | chpasswd
        EOF
}