---
- name: Image Download, Extract, Upload
  hosts: targets
  vars:
    ansible_ssh_private_key_file: ./key.pem
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    vms: [payment-web, payment-db]
  remote_user: ubuntu

  tasks:
    - name: Apt Update & Install 7z
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - p7zip-full

    - name: Snap Install AWS CLI
      become: yes
      ansible.builtin.snap:
        name:
          - aws-cli
        classic: yes

    - name: Download vms
      ansible.builtin.command: "aws s3 cp s3://cptc-vms/cptc-{{ item }}.raw.7z ./cptc-{{ item }}.raw.7z"
      async: 3000
      poll: 0
      delegate_to: "{{ play_hosts }}"
      loop: "{{ vms }}"
      loop_control:
        index_var: index
