---
- name: Linux Setup
  hosts: corp_linux
  remote_user: root
  vars:
    ansible_password: cptcadmin
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Add Scorestack User
      ansible.builtin.user:
        name: infra
        # Password is `infra`
        password: $6$balls$YFzAorVM1E0BvbNsYgkaAS2YZVxJ.Xa7N8y45N7Kjcu6ncd5WQVoRHqwn/6uQQObwMRwStu5PjPKuTQSdGY3h1
        groups:
          - root
          - admin
        shell: /bin/bash

- name: Windows Setup
  hosts: corp_windows
  remote_user: Administrator
  vars:
    ansible_password: cptcadminA1!
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Test
      ansible.windows.win_powershell:
        script: |
          slmgr -rearm
