---
- name: Linux Setup
  hosts: corp_linux
  remote_user: root
  vars:
    ansible_password: cptcadmin
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Add Scorestack User
      ansible.builtin.user:
        name: infra
        # Password is `cptcInfra12!`
        password: $6$balls$kFnVcVsrkLZXbOTBYsNXlibkcwq2eRG68btPRgX6kW2xpGDY5V1v0TW4tSHJLpwERVmHX0MR07EAnnvjRI1g70
        groups:
          - root
          - admin
        shell: /bin/bash

- name: Create Windows User
  hosts: corp_dc, corp_windows, guest_windows

  tasks:
    - name: Create Infra User
      ansible.windows.win_user:
        name: infra
        password: cptcInfra12!
        state: present

    - name: Rearm Windows License
      ansible.builtin.win_shell: cscript C:\Windows\System32\slmgr.vbs -rearm

    - name: Reboot
      ansible.windows.win_reboot:

- name: Add Windows Non-DC Usersto Group
  hosts: corp_windows, guest_windows

  tasks:
    - name: Add users to group
      ansible.windows.win_group_membership:
        name: Administrators
        members:
          - infra

- name: Add Windows DC User to Group
  hosts: corp_dc

  tasks:
    - name: Add Infra User to groups
      ansible.windows.win_powershell:
        script: |
          Add-ADGroupMember -Identity {{ item }} -Members infra
      loop: "{{ infra_groups.split(',') }}"
